
if (MSVC OR MSVC_IDE)
add_definitions(-WX)
SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -ZI")
SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -ZI")
endif()

if (CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX )
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS_DEBUG} -Wall -Werror")
if(CMAKE_SYSTEM_NAME STREQUAL "SunOS")
set_property(GLOBAL PROPERTY LINK_FLAGS "${LINK_FLAGS} -mimpure-text")
endif()
endif()

