/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_cryp7_range_hello_NativeOutput */

#ifndef _Included_net_cryp7_range_hello_NativeOutput
#define _Included_net_cryp7_range_hello_NativeOutput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_cryp7_range_hello_NativeOutput
 * Method:    output
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_cryp7_range_hello_NativeOutput_output
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
